services:
  floral:
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - floral-network

  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/postgresql/data
    networks:
      - floral-network

volumes:
  pgdata:

networks:
  floral-network: