spring:
  application:
    name: Floral Decor
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: true
    ignore-future-migrations: true
    connect-retries: 3
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: off
  logging:
    level:
      root: DEBUG
      com.domohai.floral: DEBUG
      org:
        springframework.security: DEBUG
        flywaydb: DEBUG

debug: false

auth:
  jwt:
    secret: ${SECRET_KEY}
    expiration: ${EXPIRE_TIME}

#server:
  #  servlet:
    #    context-path: /api # All APIs start with "/api"